### ISSUE TITLE
Accessory type and battery status

### ISSUE THREAD

**Issue by m-ruhl** [iRayanKhan/homebridge-roomba2#11]
Hey,

with the original plugin.. I could display the Roomba as a ventilator rather than a simple switch.
I liked it, so I can distinguish it from other devices.

This has also the benefit, that the Home-App will show the battery status and if it's charging.

**Comment by iRayanKhan** [comment]
Hey there @m-ruhl,

Not sure what you mean by displaying it as a "ventilator". Do you mean a fan? If so you can change it in the home app.

You can also currently view the battery, and charging status in the home app, if you 3D Touch on the switch two times. (It's inconvenient I know, I am working on a fix).

**Comment by m-ruhl** [comment]
Thanks for the quick reply..

Oh, yes I meant fan ;-) 

This is the screenshot with the `homebridge-roomba-stv` plugin
![IMG_1569](https://user-images.githubusercontent.com/867772/99558134-b19ab600-29c3-11eb-9a1b-01922ef70b2d.PNG)

As you can see.. I can change the device with "Display as" and see the battery status..

With your plugin I don't have that.. I think its exposed as another device type..
![IMG_1570](https://user-images.githubusercontent.com/867772/99558370-f292ca80-29c3-11eb-816a-87c8b957a3b0.PNG)

**Comment by iRayanKhan** [comment]
If you click on Accessories, then the switch, 3D Touch on it, and you can view in there. It's a limitation due to the sensors, but as I said, I am working to separate them.

**Comment by m-ruhl** [comment]
Ah sorry now I get it..
This is the parent with 2 child accessories ^^
