### ISSUE TITLE
Roomba lights always on during stand-by

### ISSUE THREAD

**Issue by andreinanu** [iRayanKhan/homebridge-roomba2#18]
### Expected Behavior
Roomba lights to stay off during stand-by/charging, as normal (maybe light up only when opening the Home app?).

### Current Behavior
Roomba lights always on if "AutoRefresh" and/or "KeepAlive" are enabled.
If both of the options are disabled, Roomba shows as Not Responding in Home app, along with all other homebridge accessories.

### Versions

- **Homebridge**: `1.1.6`
- **Node**:       `v14.15.0`
- **Plugin**:        1.2.0

### Configuration
Current config, masking bild, pwd and IP:
```
        {
            "name": "Mimosa",
            "model": "675",
            "blid": "XXXXX",
            "robotpwd": "XXXXX",
            "ipaddress": "XXXXX",
            "autoRefreshEnabled": false,
            "keepAliveEnabled": false,
            "dockContactSensor": true,
            "runningContactSensor": true,
            "binContactSensor": true,
            "accessory": "Roomba2"
        }
```

### Homebridge Log / Command Output
Homebridge logs show no errors
```
[06/12/2020, 12:10:02] [Mimosa] Roomba[{"running":0,"charging":1,"batteryLevel":100,"batteryStatus":0,"binFull":false,"binStatus":0}]
[06/12/2020, 12:10:03] [Mimosa] Connected to Roomba
```

**Comment by whreams** [comment]
Not seeing this behavior.  Roomba status is reflecting as expected.  Roomba model is an s9 with slightly different config.  FYI...  Version of HB UI is -most current production version and Node.js v12.16.3. 


            "name": "Rosie",
            "model": "s9",
            "blid": "xxxx",
            "robotpwd": "xxxx",
            "ipaddress": "xxxx",
            "dockContactSensor": true,
            "binContactSensor": true,
            "cacheTTL": 30,
            "accessory": "Roomba2"

**Comment by andreinanu** [comment]
I've managed to work around it: I've enabled AutoRefresh and set TTL Cache to 1800. Now all HB devices are refreshing normally, and the Roomba only lights up every 30 mins and stays on for 1 min, then turns off. I believe it's a good option, so I'm closing the issue.
