### ISSUE TITLE
Full bin status/notification?

### ISSUE THREAD

**Issue by sCrunch021** [iRayanKhan/homebridge-roomba2#2]
Thanks for making this plugin!

Any plans for Roomba bin status to completely replace using the official app?

**Comment by iRayanKhan** [comment]
I can add this, but not sure how I'd give the notification. Contact sensor again?

**Comment by sCrunch021** [comment]
Maybe a bin status wherever possible like battery percentage, plus a contact sensor for the notification if that’s how it works?

**Comment by iRayanKhan** [comment]
I could just make a bulb that has battery %, I need to learn how to separate battery percentages.

**Comment by iRayanKhan** [comment]
👀
![image](https://user-images.githubusercontent.com/34495712/97522401-aed11600-196d-11eb-9f2e-03e9699e20fe.png)

**Comment by sCrunch021** [comment]
Ayy that’s it

**Comment by iRayanKhan** [comment]
I'm not entirely sure if the works, if you don't mind testing this, type the following in the command line:
```
sudo  npm i -g homebridge-roomba2@1.1.0-beta.1
```

Ignore the errors on install.

**Comment by sCrunch021** [comment]
Working for me! Thanks!

![FE830C25-691D-4094-91A6-86525FAB45A3](https://user-images.githubusercontent.com/37467119/97639726-86045b80-1a15-11eb-83a6-219f8be0dcdf.jpeg)

**Comment by iRayanKhan** [comment]
Sweet! I'll merge it in tonight!
